ALTER SESSION SET "_oracle_script" = TRUE;

CREATE TABLESPACE TS_ZSS
    DATAFILE 'TS_ZSS.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M;
    
DROP TABLESPACE TS_ZSS INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE TS_ZSS_TEMP
    TEMPFILE 'TS_ZSS_TEMP.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 20M;

DROP TABLESPACE TS_ZSS_TEMP INCLUDING CONTENTS AND DATAFILES;

SELECT TABLESPACE_NAME, STATUS, CONTENTS LOGGING FROM SYS.DBA_TABLESPACES;
SELECT FILE_NAME, TABLESPACE_NAME, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, MAXBYTES, USER_BYTES FROM DBA_TEMP_FILES;

CREATE ROLE RL_ZSSCORE;
GRANT CREATE SESSION,
    CREATE TABLE, DROP ANY TABLE, ALTER ANY TABLE,
    CREATE VIEW, DROP ANY VIEW,
    CREATE PROCEDURE, DROP ANY PROCEDURE, ALTER ANY PROCEDURE
    TO RL_ZSSCORE;

DROP ROLE RL_ZSSCORE;
SELECT * FROM DBA_ROLES ;
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_ZSSCORE';

CREATE PROFILE PF_ZSSCORE LIMIT
    PASSWORD_LIFE_TIME 180 -- дни жизни пароля
    SESSIONS_PER_USER 3 -- кол-во сессий для пользователя
    FAILED_LOGIN_ATTEMPTS 7 -- кол-во попыток входа
    PASSWORD_LOCK_TIME 1 -- кол-во дней блокирования после ошибок
    PASSWORD_REUSE_TIME 10 -- через сколько дней можно повторить пароль
    PASSWORD_GRACE_TIME DEFAULT -- кол-во дней предупреждений о смене пароля
    CONNECT_TIME 180 -- время соединения, минут
    IDLE_TIME 30; -- кол-во минут простоя
    
DROP PROFILE PF_ZSSCORE;

SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_ZSSCORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

CREATE USER C##ZSSCORE IDENTIFIED BY 12345
    DEFAULT TABLESPACE TS_ZSS QUOTA UNLIMITED ON TS_ZSS
    TEMPORARY TABLESPACE TS_ZSS_TEMP
    PROFILE PF_ZSSCORE
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;

DROP USER C##ZSSCORE;
select username from all_users where username = 'C##ZSSCORE';
GRANT RL_ZSSCORE TO C##ZSSCORE;

CREATE TABLE ZSS_T (
    id number(3),
    s varchar2(50)
);

INSERT INTO ZSS_T (id, s)  VALUES (1, 'Vasya');
INSERT INTO ZSS_T (id, s)  VALUES (2, 'Sergey');
INSERT INTO ZSS_T (id, s)  VALUES (3, 'Roman');

SELECT * FROM ZSS_T;

ALTER USER C##ZSSCORE QUOTA 2M ON TS_ZSS;

INSERT INTO ZSS_T (id, s)  VALUES (4, 'Ignat');
INSERT INTO ZSS_T (id, s)  VALUES (5, 'Petr');
INSERT INTO ZSS_T (id, s)  VALUES (6, 'Matvey');

ALTER TABLESPACE TS_ZSS OFFLINE;
SELECT * FROM ZSS_T;

ALTER TABLESPACE TS_ZSS ONLINE;
SELECT * FROM ZSS_T;
 




